# server
server:
  port: 9001
  servlet:
    context-path: /uaa
# security
spring:
  security:
    user:
      name: user
      password: $2a$10$bv/dyhgcpYzHIzzM.Ivr2O.rA.v2JZeP4KKOeRAMDYehzW0O8rO0K
# log
logging:
  level:
    org.springframework.security: DEBUG