# server
server:
  port: 8001
  servlet:
    context-path: /demo
# security
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9001/uaa/oauth/token
      user-authorization-uri: http://localhost:9001/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:9001/uaa/user
      prefer-token-info: false
# log
logging:
  level:
    org.springframework.security: DEBUG